import React from 'react';
import styled from '@emotion/styled';
import Head from 'next/head';
import type { NextPage } from 'next';
import TemplateCardContainer from 'components/main/TemplateCard/TemplateCardContainer';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Readme Maker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <TemplateCardContainer />
      </Main>
    </div>
  );
};

const Main = styled.main`
  padding: 0 16px 16px;
`;

export default Home;
